using System.Collections.Generic;
using UnityEngine;
using Zenject;
using HeroesOfHarvest.Abstractions;

namespace HeroesOfHarvest
{
    /// <summary>
    /// Generated by AI (÷àñòè÷íî)
    /// </summary>
    [RequireComponent(typeof(AudioSource))]
    public class ResourcePopupSpawner : MonoBehaviour
    {
        [Inject]
        public void Initialize(IPlayerSession playerSession, IResourceIconRepository resourceIconRepository)
        {
            _playerSession = playerSession;
            _resourceIconRepository = resourceIconRepository;
        }

        public void ShowResourcePopup(Vector3 position, ResourceType type, int amount)
        {
            GameObject popupInstance = Instantiate(_moneyPopupPrefab, _ñanvas.transform);
            var popup = popupInstance.GetComponent<ResourcePopup>();
            _audioSource.PlayOneShot(_moneyAudioClip);
            if (!_resourceIconRepository.Icons.TryGetValue(type, out var icon))
            {
                icon = null;
            }
            popup.Show(amount, icon);
        }

        [SerializeField] private GameObject _moneyPopupPrefab;
        [SerializeField] private Canvas _ñanvas;
        [SerializeField] private AudioClip _moneyAudioClip;

        private AudioSource _audioSource;
        private IPlayerSession _playerSession;
        private IResourceIconRepository _resourceIconRepository;
        private readonly Dictionary<ResourceType, int> _previousResources = new();

        private void Awake()
        {
            _audioSource = GetComponent<AudioSource>();
        }
        private void OnEnable()
        {
            var resources = _playerSession.ResourceManager.GetResources();
            _previousResources.Clear();
            foreach (var resource in resources)
            {
                _previousResources[resource.Key] = resource.Value;
            }
            _playerSession.ResourceManager.ResourceChanged += OnResourceChanged;
        }
        private void OnDisable()
        {
            _playerSession.ResourceManager.ResourceChanged -= OnResourceChanged;
        }
        private void OnResourceChanged(ResourceType type, int amount)
        {
            var delta = amount - _previousResources[type];
            _previousResources[type] = amount;
            if (delta > 0)
            {
                ShowResourcePopup(_playerSession.ActiveUnit.WorldPosition, type, delta);
            }
        }
    }
}
