using System.Collections.Generic;
using UnityEngine;
using Zenject;

using KarenKrill.UniCore.Instantiattion;
using HeroesOfHarvest.Abstractions;

namespace HeroesOfHarvest
{
    /// <summary>
    /// Generated by AI (÷àñòè÷íî)
    /// </summary>
    [RequireComponent(typeof(AudioSource))]
    public class ResourcePopupSpawner : MonoBehaviour
    {
        [Inject]
        public void Initialize(IPlayerSession playerSession, IResourceIconRepository resourceIconRepository)
        {
            _playerSession = playerSession;
            _resourceIconRepository = resourceIconRepository;
        }
        public void ShowResourcePopup(Vector3 position, ResourceType type, int amount)
        {
            var popup = _itemsPool.Get();
            popup.transform.localPosition = Vector3.zero;
            _audioSource.PlayOneShot(_moneyAudioClip);
            if (!_resourceIconRepository.Icons.TryGetValue(type, out var icon))
            {
                icon = null;
            }
            popup.AnimationCompleted += OnPopupAnimationCompleted;
            popup.Show(amount, icon);
        }

        [SerializeField] private ResourcePopup _moneyPopupPrefab;
        [SerializeField] private Canvas _ñanvas;
        [SerializeField] private AudioClip _moneyAudioClip;

        private AudioSource _audioSource;
        private IPlayerSession _playerSession;
        private IResourceIconRepository _resourceIconRepository;
        private readonly Dictionary<ResourceType, int> _previousResources = new();

        [SerializeField]
        private int _defaultItemsCapacity = 10;

        private ComponentPool<ResourcePopup> _itemsPool;

        private void Awake()
        {
            _audioSource = GetComponent<AudioSource>();
            _itemsPool = new(_moneyPopupPrefab, _ñanvas.transform, _defaultItemsCapacity);
        }
        private void OnDestroy()
        {
            _itemsPool.Dispose();
        }
        private void OnEnable()
        {
            var resources = _playerSession.ResourceManager.Resources;
            _previousResources.Clear();
            foreach (var resource in resources)
            {
                _previousResources[resource.Key] = resource.Value;
            }
            _playerSession.ResourceManager.ResourceChanged += OnResourceChanged;
        }
        private void OnDisable()
        {
            _playerSession.ResourceManager.ResourceChanged -= OnResourceChanged;
        }
        private void OnResourceChanged(ResourceType type, int amount)
        {
            var delta = amount - _previousResources[type];
            _previousResources[type] = amount;
            if (delta > 0)
            {
                ShowResourcePopup(_playerSession.ActiveUnit.WorldPosition, type, delta);
            }
        }
        private void OnPopupAnimationCompleted(ResourcePopup resourcePopup)
        {
            _itemsPool.Release(resourcePopup);
        }
    }
}
